[project]
name = "microscopic-epe"
version = "0.1.0"
description = "Prostate cancer related predictions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["utils", "ml", "results"]