[project]
name = "microscopic-epe"
version = "0.1.0"
description = "Prostate cancer related predictions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dalex>=1.8.0",
    "imbalanced-learn>=0.14.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "nbformat>=5.10.4",
    "numpy>=2.4.2",
    "optuna>=4.7.0",
    "pandas>=2.3.3",
    "pip>=26.0.1",
    "scikit-learn==1.7.2", # scikit-learn 1.8.0 causes issues with DiscriminationThreshold
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
    "tableone>=0.9.6",
    "tabpfn>=6.4.1",
    "tqdm>=4.67.3",
    "xgboost>=3.2.0",
    "yellowbrick>=1.5",
]


[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["utils", "ml", "results"]
